# Generated by Django 2.2.4 on 2019-09-06 03:58


from django.db import models, migrations
from django.contrib.auth.models import Group, Permission
import logging
from django.contrib.auth.management import create_permissions


def create_group(apps, schema_editor):
    for app_config in apps.get_app_configs():
        create_permissions(app_config, apps=apps, verbosity=0)

    group, created = Group.objects.get_or_create(name='super_admin')
    if created:
        # add_thing = Permission.objects.get(codename='add_user')
        # group.permissions.add(add_thing)
        admin_permissions = [
            Permission.objects.get(codename='add_user'),
            Permission.objects.get(codename='change_user'),
            Permission.objects.get(codename='view_user'),
            Permission.objects.get(codename='delete_user'),
            Permission.objects.get(codename='add_ticket'),
            Permission.objects.get(codename='change_ticket'),
            Permission.objects.get(codename='view_ticket'),
            Permission.objects.get(codename='delete_ticket'),
        ]
        for permission in admin_permissions:
            group.permissions.add(permission)
            group.save()
    group2, created = Group.objects.get_or_create(name='senior_system_admin')
    if created:
        senior_system_admin_permissions = [
            Permission.objects.get(codename='add_ticket'),
            Permission.objects.get(codename='change_ticket'),
            Permission.objects.get(codename='view_ticket'),
            Permission.objects.get(codename='assign_to'),
            Permission.objects.get(codename='view_system_admin'),
        ]
        for permission in senior_system_admin_permissions:
            group2.permissions.add(permission)
            group2.save()

    group3, created = Group.objects.get_or_create(name='system_admin')
    if created:
        system_admin_permissions = [
            Permission.objects.get(codename='change_state'),
            Permission.objects.get(codename='view_ticket'),
        ]

        for permission in system_admin_permissions:
            group3.permissions.add(permission)
            group3.save()


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_group),
    ]