# Generated by Django 2.2.4 on 2019-09-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20190903_1208'),
    ]

    operations = [
    ]
