# Generated by Django 2.2.4 on 2019-09-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20190904_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('CRT', 'created'), ('PRG', 'in progress'), ('DNE', 'done'), ('CAN', 'cancelled')], default='CRT', max_length=3),
        ),
    ]
